carts/urls.py
from django.urls import path

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        )

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/',cart_update, name='update'),
    path('checkout/',checkout_home, name='checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from productapp.views import (
        ProductListView,
        ProductDetailView,
        ProductFeaturedListView,
        ProductFeaturedDetailView,
        ProductDetailSlugView
        )

from accounts.views import login_page, register_page, guest_register_view

from .views import contact_page, home_page

from django.conf import settings

from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('products/', include(('productapp.urls','productapp'), namespace='products')),
    path('search/', include(('search.urls','search'), namespace='search')),
    path('carts/', include(('carts.urls','cart'), namespace='cart')),

    path('products/<slug>/', ProductDetailSlugView.as_view()),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('bootstrap',TemplateView.as_view(template_name='bootstrap/example.html'))
    # path('products/<pk>', ProductDetailView.as_view()),
    # path('featured/', ProductFeaturedListView.as_view()),
    # path('featured/<pk>/', ProductFeaturedDetailView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

productapp/urls.py
from django.urls import path

from .views import (
        ProductListView,
        ProductDetailSlugView
        )

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>', ProductDetailSlugView.as_view(), name='detail'),
]

templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Fontawesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/base/nav.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'logout' as logout_url %}

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
  <a class="navbar-brand" href="{{home_url}}">
  <img src="https://getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg"
      width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
    {% if brand_name %} {{brand_name}}
    {% else %}
    Welcome Kalash
    {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{contact_url}}">Contact Us</a>
      </li>
      <li class="nav-item {% if request.path == products_url %}active{% endif %}">
        <a class="nav-link" href="{{products_list_url}}">Products</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{logout_url}}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{login_url}}">Login</a>
      </li>
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{register_url}}">Register</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link"  href="{{cart_url}}"><b style="color:white;"> {{ request.session.cart_items}} </b><i class="fa fa-shopping-cart" aria-hidden='true'></i></a>
      </li>
      <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown link
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Sports</a>
                <a class="dropdown-item" href="#">Fashion</a>
                <a class="dropdown-item" href="#">Electronics</a>
              </div>
      </li> -->
    </ul>
      {% include "search/snippets/search-form.html"%}
  </div>
</div>
</nav>